# TUGAS 8

**ENSEMBLE LEARNING (BAGGING DAN RANDOM FOREST)**

**BAGGING**

Bagging adalah proses dengan menggunakan beberapa model dari algoritma yang sama dan melatih setiap model pada sampel berbeda dari dataset yang sama. 

Prediksi yang dibuat oleh setiap model kemudian digabungkan menggunakan statistik sederhana seperti voting atau rata - rata.

**RANDOM FOREST**

Random Forest adalah kumpulan dari decision tree atau pohon keputusan. 

Algoritma ini merupakan kombinasi masing - masing tree dari desicion tree yang kemudian digabungkan menjadi satu model. Digunakan untuk masalah regresi dan klasifikasi.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC

In [ ]:
dataset = "https://raw.githubusercontent.com/FirdatulFitriyah/datamining/main/credit_score.csv"
data = pd.read_csv(dataset)
data

Unnamed: 0 kode_kontrak  pendapatan_setahun_juta kpr_aktif  \
0             1   AGR-000001                      295        YA   
1             2   AGR-000011                      271        YA   
2             3   AGR-000030                      159     TIDAK   
3             4   AGR-000043                      210        YA   
4             5   AGR-000049                      165     TIDAK   
..          ...          ...                      ...       ...   
895         896   AGR-010739                      112        YA   
896         897   AGR-010744                      120        YA   
897         898   AGR-010758                      166     TIDAK   
898         899   AGR-010775                      196     TIDAK   
899         900   AGR-010790                      204     TIDAK   

     durasi_pinjaman_bulan  jumlah_tanggungan rata_rata_overdue  risk_rating  
0                       48                  5      61 - 90 days            4  
1                       36                  5      61 - 90 days            4  
2                       12                  0       0 - 30 days            1  
3                       12                  3      46 - 60 days            3  
4                       36                  0      31 - 45 days            2  
..                     ...                ...               ...          ...  
895                     48                  5         > 90 days            5  
896                     48                  2      46 - 60 days            3  
897                     24                  2       0 - 30 days            1  
898                     48                  0      31 - 45 days            2  
899                     24                  2       0 - 30 days            1  

[900 rows x 8 columns]

In [ ]:
data.head()
data1 = data.drop(columns=['kpr_aktif', 'rata_rata_overdue'])

Data1 = Data tanpa kpr_aktif dan rata rata overdue

In [ ]:
data2 = data[["kpr_aktif"]]

data2 = data Kpr_Aktif

In [ ]:
data2.head(25)

kpr_aktif
0         YA
1         YA
2      TIDAK
3         YA
4      TIDAK
5      TIDAK
6      TIDAK
7      TIDAK
8      TIDAK
9      TIDAK
10     TIDAK
11     TIDAK
12     TIDAK
13     TIDAK
14     TIDAK
15     TIDAK
16        YA
17     TIDAK
18     TIDAK
19     TIDAK
20     TIDAK
21     TIDAK
22     TIDAK
23     TIDAK
24     TIDAK

Merubah String data menjadi numerik

In [ ]:
datakpr = pd.get_dummies(data2)
datakpr

kpr_aktif_TIDAK  kpr_aktif_YA
0                  0             1
1                  0             1
2                  1             0
3                  0             1
4                  1             0
..               ...           ...
895                0             1
896                0             1
897                1             0
898                1             0
899                1             0

[900 rows x 2 columns]

datakpr = data kpr yang sudah diubah menjadi angka

In [ ]:
data3 = data[["rata_rata_overdue"]]

data3 = data rata-rata_overdue

In [ ]:
data3.head(25)

rata_rata_overdue
0       61 - 90 days
1       61 - 90 days
2        0 - 30 days
3       46 - 60 days
4       31 - 45 days
5        0 - 30 days
6       31 - 45 days
7       31 - 45 days
8       31 - 45 days
9       31 - 45 days
10      31 - 45 days
11      31 - 45 days
12      31 - 45 days
13      31 - 45 days
14      31 - 45 days
15      31 - 45 days
16       0 - 30 days
17       0 - 30 days
18       0 - 30 days
19      31 - 45 days
20      31 - 45 days
21      31 - 45 days
22       0 - 30 days
23       0 - 30 days
24       0 - 30 days

In [ ]:
datarata = pd.get_dummies(data3)

In [ ]:
datarata

rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
..                           ...  
895                            1  
896                            0  
897                            0  
898                            0  
899                            0  

[900 rows x 5 columns]

In [ ]:
datanumeric = pd.concat([datakpr, datarata], axis=1)

In [ ]:
Hasil = pd.concat([data1, datanumeric], axis=1)
Hasil

Unnamed: 0 kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0             1   AGR-000001                      295                     48   
1             2   AGR-000011                      271                     36   
2             3   AGR-000030                      159                     12   
3             4   AGR-000043                      210                     12   
4             5   AGR-000049                      165                     36   
..          ...          ...                      ...                    ...   
895         896   AGR-010739                      112                     48   
896         897   AGR-010744                      120                     48   
897         898   AGR-010758                      166                     24   
898         899   AGR-010775                      196                     48   
899         900   AGR-010790                      204                     24   

     jumlah_tanggungan  risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0                    5            4                0             1   
1                    5            4                0             1   
2                    0            1                1             0   
3                    3            3                0             1   
4                    0            2                1             0   
..                 ...          ...              ...           ...   
895                  5            5                0             1   
896                  2            3                0             1   
897                  2            1                1             0   
898                  0            2                1             0   
899                  2            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
..                           ...  
895                            1  
896                            0  
897                            0  
898                            0  
899                            0  

[900 rows x 13 columns]

Min Max Normalisasi

In [ ]:
dataNormalisasi = ['pendapatan_setahun_juta', 'durasi_pinjaman_bulan', 'jumlah_tanggungan']
FrameNormalisasi = Hasil[dataNormalisasi]
FrameNormalisasi

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan
0                        295                     48                  5
1                        271                     36                  5
2                        159                     12                  0
3                        210                     12                  3
4                        165                     36                  0
..                       ...                    ...                ...
895                      112                     48                  5
896                      120                     48                  2
897                      166                     24                  2
898                      196                     48                  0
899                      204                     24                  2

[900 rows x 3 columns]

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaler.fit(FrameNormalisasi)

MinMaxScaler()

In [ ]:
hasilNormalisasi = scaler.transform(FrameNormalisasi)

In [ ]:
hasilNormalisasi = pd.DataFrame(hasilNormalisasi,columns = dataNormalisasi)
hasilNormalisasi

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan
0                   0.978261               1.000000           0.833333
1                   0.873913               0.666667           0.833333
2                   0.386957               0.000000           0.000000
3                   0.608696               0.000000           0.500000
4                   0.413043               0.666667           0.000000
..                       ...                    ...                ...
895                 0.182609               1.000000           0.833333
896                 0.217391               1.000000           0.333333
897                 0.417391               0.333333           0.333333
898                 0.547826               1.000000           0.000000
899                 0.582609               0.333333           0.333333

[900 rows x 3 columns]

In [ ]:
Hasil = Hasil.drop(columns = dataNormalisasi)
Hasil = pd.concat([Hasil, hasilNormalisasi], axis=1)
Hasil

Unnamed: 0 kode_kontrak  risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0             1   AGR-000001            4                0             1   
1             2   AGR-000011            4                0             1   
2             3   AGR-000030            1                1             0   
3             4   AGR-000043            3                0             1   
4             5   AGR-000049            2                1             0   
..          ...          ...          ...              ...           ...   
895         896   AGR-010739            5                0             1   
896         897   AGR-010744            3                0             1   
897         898   AGR-010758            1                1             0   
898         899   AGR-010775            2                1             0   
899         900   AGR-010790            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  pendapatan_setahun_juta  \
0                              0                 0.978261   
1                              0                 0.873913   
2                              0                 0.386957   
3                              0                 0.608696   
4                              0                 0.413043   
..                           ...                      ...   
895                            1                 0.182609   
896                            0                 0.217391   
897                            0                 0.417391   
898                            0                 0.547826   
899                            0                 0.582609   

     durasi_pinjaman_bulan  jumlah_tanggungan  
0                 1.000000           0.833333  
1                 0.666667           0.833333  
2                 0.000000           0.000000  
3                 0.000000           0.500000  
4                 0.666667           0.000000  
..                     ...                ...  
895               1.000000           0.833333  
896               1.000000           0.333333  
897               0.333333           0.333333  
898               1.000000           0.000000  
899               0.333333           0.333333  

[900 rows x 13 columns]

In [ ]:
label = ['Unnamed: 0','kode_kontrak']
Hasil2 = Hasil.drop(columns = label)
Hasil2

risk_rating  kpr_aktif_TIDAK  kpr_aktif_YA  \
0              4                0             1   
1              4                0             1   
2              1                1             0   
3              3                0             1   
4              2                1             0   
..           ...              ...           ...   
895            5                0             1   
896            3                0             1   
897            1                1             0   
898            2                1             0   
899            1                1             0   

     rata_rata_overdue_0 - 30 days  rata_rata_overdue_31 - 45 days  \
0                                0                               0   
1                                0                               0   
2                                1                               0   
3                                0                               0   
4                                0                               1   
..                             ...                             ...   
895                              0                               0   
896                              0                               0   
897                              1                               0   
898                              0                               1   
899                              1                               0   

     rata_rata_overdue_46 - 60 days  rata_rata_overdue_61 - 90 days  \
0                                 0                               1   
1                                 0                               1   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
895                               0                               0   
896                               1                               0   
897                               0                               0   
898                               0                               0   
899                               0                               0   

     rata_rata_overdue_> 90 days  pendapatan_setahun_juta  \
0                              0                 0.978261   
1                              0                 0.873913   
2                              0                 0.386957   
3                              0                 0.608696   
4                              0                 0.413043   
..                           ...                      ...   
895                            1                 0.182609   
896                            0                 0.217391   
897                            0                 0.417391   
898                            0                 0.547826   
899                            0                 0.582609   

     durasi_pinjaman_bulan  jumlah_tanggungan  
0                 1.000000           0.833333  
1                 0.666667           0.833333  
2                 0.000000           0.000000  
3                 0.000000           0.500000  
4                 0.666667           0.000000  
..                     ...                ...  
895               1.000000           0.833333  
896               1.000000           0.333333  
897               0.333333           0.333333  
898               1.000000           0.000000  
899               0.333333           0.333333  

[900 rows x 11 columns]

In [ ]:
percent_amount_of_test_data = 0.3

Menghitung Data
```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test
```

In [ ]:
matrices_X = Hasil2.iloc[:,1:11].values
matrices_Y = Hasil2.iloc[:,0].values

In [ ]:
X1 = Hasil2.iloc[:,1:11].values
Y1 = Hasil2.iloc[:, 0].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [ ]:
X1.shape

(900, 10)

In [ ]:
X_train.shape

(630, 10)

In [ ]:
Y1

array([4, 4, 1, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1,
       2, 2, 1, 2, 2, 4, 4, 1, 1, 1, 3, 5, 3, 3, 5, 3, 5, 3, 1, 3, 1, 3,
       5, 1, 3, 3, 5, 1, 3, 4, 2, 3, 2, 1, 4, 3, 3, 3, 1, 4, 1, 4, 3, 1,
       3, 5, 3, 5, 5, 5, 3, 5, 3, 1, 5, 5, 3, 3, 1, 5, 1, 1, 2, 3, 3, 4,
       1, 4, 1, 3, 3, 3, 3, 1, 2, 2, 3, 4, 4, 3, 2, 1, 3, 3, 3, 3, 4, 4,
       1, 3, 1, 2, 3, 3, 3, 5, 2, 3, 5, 3, 1, 5, 5, 1, 5, 5, 3, 2, 5, 3,
       5, 1, 2, 3, 3, 5, 5, 3, 1, 1, 1, 3, 1, 1, 5, 1, 3, 5, 3, 2, 3, 3,
       1, 1, 1, 3, 5, 3, 5, 2, 3, 3, 3, 1, 5, 3, 3, 3, 1, 1, 2, 1, 5, 3,
       3, 5, 4, 3, 4, 5, 3, 3, 5, 1, 1, 3, 3, 2, 3, 1, 2, 3, 1, 3, 2, 2,
       2, 4, 3, 2, 3, 1, 2, 5, 5, 4, 3, 1, 2, 2, 5, 4, 5, 2, 3, 3, 1, 3,
       5, 1, 2, 5, 3, 1, 5, 3, 1, 4, 2, 1, 3, 3, 3,

In [ ]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

Contoh terdapat Customer dengan nama "Firda"


---


*    overdue 0 - 30  days : 0
*    overdue 31 - 45 days : 1
*    overdue 46 - 60 days : 0 
*    overdue 61 - 90 days : 0
*    overdue > 90 days    : 0 
*    KPR_TIDAK : 0
*    KPR_YA	: 1
*    pendapatan_setahun_juta : 0.582609 
*    durasi_pinjaman_bulan	: 0.666667  
*    jumlah_tanggungan	: 0

Mencari risk Rating berdasarkan isi diatas

```
# Contoh Data Customer 'Putra'
[0,	1,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]

Naive Bayes

In [ ]:
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)

cm = confusion_matrix(y_test, Y_pred_nb)

print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))

Confusion matrix for Gaussian Naive Bayes
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  0 84  0  0]
 [ 0  0  0 36  0]
 [ 0  0  0  0 32]]
The accuracy of this model is 100.0 %.
The precision of this model is 100.0 %.
The recall of this model is 100.0 %.


In [ ]:
Y_pred_nb

array([2, 1, 3, 2, 4, 4, 1, 3, 3, 5, 1, 2, 5, 2, 3, 3, 1, 3, 3, 4, 2, 3,
       3, 1, 5, 3, 3, 3, 3, 3, 2, 3, 5, 3, 1, 4, 4, 4, 4, 2, 4, 1, 1, 2,
       5, 3, 5, 2, 1, 1, 2, 5, 1, 1, 2, 5, 1, 3, 3, 3, 4, 2, 3, 5, 5, 3,
       3, 3, 4, 1, 5, 4, 2, 1, 1, 4, 3, 3, 3, 5, 1, 2, 3, 2, 4, 3, 1, 3,
       2, 1, 2, 3, 2, 2, 3, 1, 2, 5, 5, 1, 1, 1, 3, 1, 5, 4, 3, 5, 2, 2,
       3, 3, 1, 1, 2, 1, 4, 4, 2, 2, 5, 4, 3, 1, 4, 1, 3, 1, 1, 5, 1, 1,
       1, 3, 3, 2, 5, 3, 1, 4, 3, 5, 3, 5, 2, 3, 1, 2, 2, 3, 3, 3, 3, 4,
       5, 3, 3, 4, 3, 1, 2, 1, 1, 1, 2, 1, 3, 1, 4, 2, 1, 1, 4, 2, 2, 1,
       1, 1, 3, 3, 3, 4, 5, 4, 3, 1, 1, 3, 2, 2, 3, 3, 4, 2, 5, 3, 5, 1,
       3, 5, 2, 3, 2, 3, 3, 2, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 2, 3, 2, 3,
       3, 1, 1, 1, 1, 5, 1, 3, 2, 1, 4, 1, 5, 4, 4, 3, 3, 3, 3, 3, 2, 3,
       1, 4, 4, 4, 3, 5, 3, 3, 1, 1, 4, 1, 5, 1, 5, 2, 1, 2, 2, 3, 4, 4,
       1, 2, 4, 2, 5, 3])

In [ ]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [ ]:
FIRST_IDX = 0

In [ ]:
# try with value [0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
result_test_naive_bayes = clf_pf.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])[FIRST_IDX]
print(f"Customer : Firda Memiliki risk rating {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Customer : Firda Memiliki risk rating 5 Pada metode Gaussian Naive Bayes model


K - Nearest Neighbors


*   Tentukan nilai K = 10 (10 tetangga terdekat)
*   Buat data latih

In [ ]:
K = 10
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
Y_pred_knn = knn.predict(X_test)

In [ ]:
knn.score(X_test, y_test)

0.9925925925925926

In [ ]:
# Custom value to predict
result_test_knn = knn.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])
print(f"Customer : Firda Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode KNN model")

Customer : Firda Memiliki risk rating 5 Pada metode KNN model


In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_knn)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for K - Nearest Neighbors\n',cm)
nn1_accuracy = round(100 * accuracy_score(y_test, Y_pred_knn), 2)
model_accuracy['1 - Nearest Neighbors'] = nn1_accuracy

nn1_precision = round(100 * precision_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_precision['1 - Nearest Neighbors'] = nn1_precision

nn1_recall = round(100 * recall_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_recall['1 - Nearest Neighbors'] = nn1_recall

print('The accuracy of this model is {} %.'.format(nn1_accuracy))
print('The precision of this model is {} %.'.format(nn1_precision))
print('The recall of this model is {} %.'.format(nn1_recall))

Confusion matrix for K - Nearest Neighbors
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  1 83  0  0]
 [ 0  0  0 36  0]
 [ 0  1  0  0 31]]
The accuracy of this model is 99.26 %.
The precision of this model is 99.29 %.
The recall of this model is 99.26 %.


Decision Tree

In [ ]:
### Applying Decision Tree Classification model

decision_tree_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 27)
decision_tree_classifier.fit(X_train, y_train)


### Predicting the Test set results

Y_pred_dc = decision_tree_classifier.predict(X_test)

In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Decision Tree\n',cm)

decision_tree_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Decision Tree'] = decision_tree_accuracy

decision_tree_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Decision Tree'] = decision_tree_precision

decision_tree_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Decision Tree'] = decision_tree_recall

print('The accuracy of this model is {} %.'.format(decision_tree_accuracy))
print('The precision of this model is {} %.'.format(decision_tree_precision))
print('The recall of this model is {} %.'.format(decision_tree_recall))

Confusion matrix for Decision Tree
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  0 84  0  0]
 [ 0  0  0 36  0]
 [ 0  0  1  0 31]]
The accuracy of this model is 99.63 %.
The precision of this model is 99.63 %.
The recall of this model is 99.63 %.


In [ ]:
# Custom value to predict
result_test_knn = decision_tree_classifier.predict([[0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]])
print(f"Customer : Firda Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode Decision Tree model")

Customer : Firda Memiliki risk rating 5 Pada metode Decision Tree model


Bagging Ensemble

In [ ]:
clf = BaggingClassifier(base_estimator=DecisionTreeClassifier(),n_estimators=10, random_state=0).fit(X_train, y_train)
rsb = clf.predict(X_test)
b = ['Decision Tree']
Tree = pd.DataFrame(rsb,columns = b)

In [ ]:
X_test.shape

(270, 10)

In [ ]:
clf = BaggingClassifier(base_estimator=KNeighborsClassifier(n_neighbors = K),n_estimators=10, random_state=0).fit(X_train, y_train)
rsa = clf.predict(X_test)
a = ['KNN']
KNN = pd.DataFrame(rsa,columns = a)

In [ ]:
clf = BaggingClassifier(base_estimator=GaussianNB(),n_estimators=10, random_state=0).fit(X_train, y_train)
rsc = clf.predict(X_test)
c = ['Naive Bayes']
Bayes = pd.DataFrame(rsc,columns = c)

In [ ]:
Result = pd.concat([Tree, KNN,Bayes], axis=1)
Result

Decision Tree  KNN  Naive Bayes
0                2    2            2
1                1    1            1
2                3    3            3
3                2    2            2
4                4    4            4
..             ...  ...          ...
265              2    2            2
266              4    4            4
267              2    2            2
268              5    5            5
269              3    3            3

[270 rows x 3 columns]

In [ ]:
bagging_accuracy1 = round(100 * accuracy_score(y_test, Bayes), 2)
bagging_accuracy2 = round(100 * accuracy_score(y_test, Tree), 2)
bagging_accuracy3 = round(100 * accuracy_score(y_test, KNN), 2)
print('The accuracy of this model is Bagging Naive Bayes {} %.'.format(bagging_accuracy1))
print('The accuracy of this model is Bagging Decision Tree {} %.'.format(bagging_accuracy2))
print('The accuracy of this model is Bagging kNN {} %.'.format(bagging_accuracy3))

The accuracy of this model is Bagging Naive Bayes 100.0 %.
The accuracy of this model is Bagging Decision Tree 100.0 %.
The accuracy of this model is Bagging kNN 99.63 %.
